import logging
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from typing import Dict, Any, List

from app.api.auth import get_current_user
from app.models.user import User
from app.agents.coordinator import run_cfo_pipeline
from app.services.scheduler_service import get_proactive_notifications
from app.services.qdrant_service import qdrant_service

logger = logging.getLogger("api.chat")
router = APIRouter(prefix="/chat", tags=["chat"])

# In-memory store for the latest telemetry trace per user
latest_traces: Dict[str, Dict[str, Any]] = {}

class QueryRequest(BaseModel):
    message: str

@router.post("")
async def ask_cfo(body: QueryRequest, current_user: User = Depends(get_current_user)):
    """Receives a user question, runs it through the A2A pipeline, and returns the result with telemetry."""
    if not body.message.strip():
        raise HTTPException(status_code=400, detail="Query message cannot be empty")
        
    try:
        result = await run_cfo_pipeline(user_id=current_user.id, query=body.message)
        # Store latest telemetry trace
        latest_traces[current_user.id] = result.get("telemetry", {})
        return result
    except Exception as e:
        logger.error(f"Coordinator execution failed: {e}")
        raise HTTPException(status_code=500, detail=f"Agent pipeline error: {e}")

@router.get("/history")
def get_chat_history(current_user: User = Depends(get_current_user)) -> List[Dict[str, str]]:
    """Loads historical conversation logs of user queries and CFO agent responses from vector memory."""
    try:
        history = qdrant_service.get_conversation_history(user_id=current_user.id)
        formatted = []
        for h in history:
            content = h.get("content", "")
            if "User asked: " in content and ". Recommendation: " in content:
                parts = content.split(". Recommendation: ")
                user_prompt = parts[0].replace("User asked: ", "").strip()
                cfo_rec = parts[1].strip()
                formatted.append({"sender": "user", "text": user_prompt})
                formatted.append({"sender": "cfo", "text": cfo_rec})
            else:
                formatted.append({"sender": "cfo", "text": content})
        return formatted
    except Exception as e:
        logger.error(f"Error compiling chat history: {e}")
        return []

@router.get("/trace")
def get_latest_trace(current_user: User = Depends(get_current_user)) -> Dict[str, Any]:
    """Retrieves the telemetry details of the last executed ADK pipeline run."""
    trace = latest_traces.get(current_user.id)
    if not trace:
        return {
            "total_execution_time_ms": 0.0,
            "qdrant_memory_retrievals": 0,
            "qdrant_rag_hits": 0,
            "trace": []
        }
    return trace

@router.get("/notifications")
def get_coaching_alerts(current_user: User = Depends(get_current_user)) -> List[Dict[str, Any]]:
    """Retrieves list of active alerts generated by background budget calculations."""
    return get_proactive_notifications(user_id=current_user.id)

